### ISSUE TITLE
Add the ability to add php-fpm pool config like php

### ISSUE THREAD

**Issue by wizhippo** [ezsystems/docker-php#50]
It would be nice to be able to do similar to add PHP_INI_ENV such as PHP_FPM_INI_ENV for fpm paramters leil

PHP_FPM_INI_ENV _pm.max_children=10

**Comment by andrerom** [comment]
PR welcome :)

**Comment by wizhippo** [comment]
Sure thing https://github.com/ezsystems/docker-php/pull/51

**Comment by mnocon** [comment]
Added in https://github.com/ezsystems/docker-php/pull/51
